server:
  port: 8001
spring:
  application:
    name: gateway
#gateway的配置
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
    gateway:
      #路由规则
      routes:
        - id: music-service #路由唯一标识
          uri: lb://music-service #需要转发的地址   lb 负载均衡策略
          #断言规则
          predicates:
            - Path=/music-service/**
          filters:
            - StripPrefix = 1 #转发前去掉前n个路径

      #跨域相关配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "*"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期